# Generated by Django 4.2.11 on 2024-10-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookHub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='de',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='para',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='livrosFavoritos',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
